"""empty message

Revision ID: 40d7ecfcd4e5
Revises: 
Create Date: 2018-02-23 16:35:14.557966

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from app.models import FeedbackPost


# revision identifiers, used by Alembic.
revision = '40d7ecfcd4e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('feedback_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cohort', sa.Integer(), nullable=True),
    sa.Column('track', sqlalchemy_utils.types.choice.ChoiceType(FeedbackPost.TYPES), nullable=True),
    sa.Column('curriculumGrade', sa.Integer(), nullable=True),
    sa.Column('curriculumComment', sa.String(length=500), nullable=True),
    sa.Column('projectGrade', sa.Integer(), nullable=True),
    sa.Column('projectComment', sa.String(length=500), nullable=True),
    sa.Column('carDevGrade', sa.Integer(), nullable=True),
    sa.Column('carDevComment', sa.String(length=500), nullable=True),
    sa.Column('overallGrade', sa.Integer(), nullable=True),
    sa.Column('overallComment', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_post_timestamp'), 'feedback_post', ['timestamp'], unique=False)
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_table('followers')
    op.drop_index(op.f('ix_feedback_post_timestamp'), table_name='feedback_post')
    op.drop_table('feedback_post')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
